language: cpp
dist: trusty
compiler:
  - gcc

# add the patch
before_install:
- patch -p1 < patch/festival/festival.patch
- patch -p1 < patch/install/player_3.0.2_14.04.patch
- patch -p1 < patchdonnie/instalationSoundProxy.patch

# Install all of the dependencies:
install:
  - sudo apt-get -qq update

# Execute all of the commands which should make the build pass or fail
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -DDEBUG_LEVEL=NONE -BUILD_PYTHONC_BINDINGS:BOOL=OFF -DCMAKE_INSTALL_PREFIX=$(pwd)/install ..
  - make
  - make install
